name: Maven Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
        java: ['11.0.4', '12.0.2']
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Install JDK ${{matrix.java}}
      uses: actions/setup-java@v1
      with:
        java-version: ${{matrix.java}}
        architecture: x64
    - name: Build with Maven
      run: mvn verify --file pom.xml
